### ISSUE TITLE
Expose `fup-repl` through `blueprints`

### ISSUE THREAD

**Issue by examosa** [gytis-ivaskevicius/flake-utils-plus#127]
I am using [std](https://github.com/divnix/std) to configure my repository and want to [avoid using overlays](https://github.com/divnix/std/blob/f9129df3099aab7f3f5eac57e111666d6d136eaf/docs/explain/architecture-decision-records/0006-avoid-fix-point-logic-such-as-overlays.md) where feasible. To that end, I've been using the `packages` output that most overlays expose (see [emacs-overlay](https://github.com/nix-community/emacs-overlay) as a good example). Would it be possible for `fup-repl` to be made available this way as well?

**Comment by gytis-ivaskevicius** [comment]
Hi, sorry for the late response. In short - no, due to this project's avoidance to depend on nixpkgs.

Once I get to it I'll expose it as a blueprint (https://github.com/gytis-ivaskevicius/nix-patterns/blob/master/07-blueprints-no-nixpkgs/flake.nix#L7)

In a meanwhile may I recommend something like this:
```
fup-repl = (flake-utils-plus.overlay pkgs null).fup-repl;
```

TODO: 
- Update flake schema
- Add bluerpints
