### ISSUE TITLE
Enforce `inputs` in overlays

### ISSUE THREAD

**Issue by gytis-ivaskevicius** [gytis-ivaskevicius/flake-utils-plus#47]
Shall we add something along the lines of this by default to `sharedOverlays` so people could easily define `src = inputs.someGitRepo;` in their packages
```nix
final: prev: { inherit inputs; }
```

I got something similar setup https://github.com/gytis-ivaskevicius/nixfiles/blob/master/flake.nix#L140 - obviously, this would crash if consumers do not have something like that already defined. But then again - that's probably the best way to pass inputs down to overlays

**Comment by blaggacao** [comment]
In my opinion it would be good to separate sources from other inputs. The list might grow quickly enough in some cases to get confusing as to what is the raison d'etre of each input (src vs other poilerplate inputs).

One advantage of the subflake approach used by devos is to quickly update all sources (and only sources) at once with nix flake update.

```
inputs.src.url = path:./pkgs;
# also adds a way to infer meaningful version strings from flake.lock file there to use with the package's `version` attr
```

```
{lib, pkgs, srcs}:
...
src = srcs.${pname};
version= srcs.${pname}.version;

...

```

**Comment by gytis-ivaskevicius** [comment]
I don't think a lot of people wish to bother with separate flakes since most people have just a few extra repos in their flakes. ( And I am no exception :) )

But from what I see - instead of `inputs` you are just passing `srcs`. It does not change much? Also, same compatibility problem exists? Or is it that I am not getting something?

**Comment by blaggacao** [comment]
Devos does exactly the same thing just for the `./pkgs` subflake:

https://www.github.com/divnix/devos/tree/core/pkgs%2Fflake.nix

I see both approaches mostly equivalent so the only thing that would worsen the state of the (broader) world, would be to produce both alternatives.

@nrdxp what do you think?

**Comment by blaggacao** [comment]
In any case we should strongly lobby for inputs to contain in addition to `inputs.rev` an `inputs.ref` so that we can extract meaningful (for a human) version information out of tags. Can't find the issue right now that I opened ages ago upstream nix.

We then could argue:
- pkgs are equivalence substitutes for missing upstream overlays
- we also put overlays inputs in the top level flake
- why shouldn't we do the same for their equivalence substitutes

- we also should name it `srcs` and filter inputs on `flake = false;`. That's a reasonable distinction for separate the flake natives from those that _possibly_ could require treatment within `./pkgs`

**Comment by Pacman99** [comment]
I would be against passing all inputs by default since it would encourage people to pull packages from inputs instead of doing it properly in their flake.nix with overlaysBuilder or sharedOverlays. 

I do like the goal of auto-updating sources. I know devos does this, but I actually prefer other tools just because of how finicky subflaking is and without sub flaking I would end up adding a lot of input lines to my flake. 

Also many nixpkgs packaging paradigms require more than just updating a src - cargo hash, go hash, nodejs deps files. So its not a very effective method of auto-updating packages, it only works for a few packages.

I think a dedicated tool like [nix-update](https://github.com/Mic92/nix-update) is a better method overall.

**Comment by gytis-ivaskevicius** [comment]
I feel like it is not exactly about "what is the right way to do it", I'd say it's more of a "How users will use `fup`/`devos` and what is the most convenient for them".

Updating sources using the flake does not cover all cases - but it does cover most of them. 

@blaggacao I do like the filtering where `flake = false` idea  :+1: 

And honestly - it's not exactly relevant but I do dislike all ideas mentioned above. Maybe it would be worth building some dedicated tool inspired by https://github.com/colemickens/nixpkgs-wayland They seem to have a solid update setup going there. It would give us much, much more power and control over the dependencies and I can already think of some actually pretty sick features that could be implemented which would strongly complement nixpkgs

**Comment by blaggacao** [comment]
Let's do filtering on `flake  = false` and pass it as `srcs`, **but** not as an addition to the input (because we are already reasoning about explicitly user set overlays and derive logic thereof), but as a hard coded addition within the belly of systemFlake.nix

**Comment by blaggacao** [comment]
Here is the upstream issue that would allow to access decent version info: https://github.com/NixOS/nix/issues/3838

Please restate that point, if you agree.

**Comment by gytis-ivaskevicius** [comment]
The issue makes a lot of sense - but I find it difficult to agree with it because from my point of view package sources should be approached in a different manner. (This includes nixpkgs too, not only users like us)

I think somewhat soon (maybe this weekend?) I'll write up some sort of proposal and will check-up with the community to see what they think

**Comment by blaggacao** [comment]
I'll be very keen on reading it. I also have a sense, we might be heading to another **local** maximum.
