### ISSUE TITLE
`xyzBuilder = channels: {..}` should be replaced with `exports = channels: { packages = ...; apps = ...;}`

### ISSUE THREAD

**Issue by gytis-ivaskevicius** [gytis-ivaskevicius/flake-utils-plus#56]
I have no idea why fup does not implement just a single builder for everything - but now that I look at it - it's obvious that this would be quite a bit nicer way of handling things. 

Possible issues:
Merging logic, it's always has been a pain. Tho if I recall correctly existing `mergeAny` function should just work out of the box

Expected outcome:
```nix
utils.lib.systemFlake {

  exports = channels: { 
    packages = { 
      inherit (channels.nixpkgs) hello coreutils neovim; 
    };
    
    apps = {
      neovim = mkApp {
        drv = channels.nixpkgs.neovim;
        exePath = "/bin/nvim";
      };   
    };

    checks = { 
      inherit (channels.nixpkgs) hello coreutils neovim; 
    };
    # ... etc ...
  };

}
```

@blaggacao @Pacman99 Looks good?

**Comment by blaggacao** [comment]
Looks good, let's make it `outputs =` instead of `exports =`. Rhe name "exports" was once proposed in the community for rhe non-package-dependent outputs (like modules & overlays)

**Comment by gytis-ivaskevicius** [comment]
I am definitely open to naming suggestions but i am not sure if `outputs` is the right word for it since i got a feeling that it will confuse users. 
Basically, I'd rather avoid duplicating keyword `outputs` like so:

```nix
{
  # outputs #1
  outputs = { self, utils, nixpkgs}@inputs:
    utils.lib.systemFlake {
      inherit self inputs;
      
      # outputs #2
      outputs = channels: {
        # ...
      };
    };
}
```

**Comment by blaggacao** [comment]
Oh true, I havn't seen that coming. Let's stick with "exports", then.

**Comment by Pacman99** [comment]
Yeah I like it, the interface is much cleaner.
For devos's mkFlake - which we're trying to maintain as a wrapper of systemFlake - we could do something like this:
```nix
exports = channels: lib.mergeAny {
  packages = lib.builder.packagesFromOverlaysBuilderConstructor self.overlays channels;
} (otherArguments.exports channels);
```
Also we should probably rename packagesFromOverlaysBuilderConstructor, and maybe the other one too.

But we definitely need a different name than `exports` or `outputs`. I think enough people have read this proposal: https://github.com/NixOS/nix/issues/3843#issuecomment-661720562, for that to be counter-productive. Even though that proposal might not be implemented, we would be directly opposing it by using the `exports` name that was suggested for non-system based outputs. And as you said, `outputs` is confusing because of the duplicate naming.

Random ideas:
 - systemOutputs
 - outputsBuilder
 - products

I like outputsBuilder because it has a direct connection to the previous arguments.

**Comment by gytis-ivaskevicius** [comment]
Implemented in https://github.com/gytis-ivaskevicius/flake-utils-plus/pull/59
