### ISSUE TITLE
fup-repl non-reproducible

### ISSUE THREAD

**Issue by blaggacao** [gytis-ivaskevicius/flake-utils-plus#71]
https://github.com/gytis-ivaskevicius/flake-utils-plus/blob/6b2ea4b02cad77fac581c6a9ec4f822ba87dce5c/lib/systemFlake.nix#L54-L63

Looks like this script does not fetch reproducible `nix` or `sed` from `pkgs`.

**Comment by Pacman99** [comment]
This isn't an issue on nixos since both unstable nix and gnused are guaranteed to exist on a nixos system. And since this is done as an overlay, fup-repl can only be used on a system built with fup.

I mean we can do `pkgs.nixUnstable` and `pkgs.gnused` but I think it would be really redundant.

**Comment by blaggacao** [comment]
Oh very intricate circumstances, indeed. :wink:

Let's do the real thing instead of adding a comment explaining this.

I think, we should continue to care to be explicit, whenever we can.

**Comment by Pacman99** [comment]
> I mean we can do pkgs.nixUnstable and pkgs.gnused but I think it would be really redundant.


Actually I think using `pkgs.nixUnstable` would be a bad idea since we dont have access to `nix.package`. So if someone has overriden `config.nix.package` we would be using the wrong nix and more importantly adding a extra dependency to their system. I'm ok with doing it for `sed`, but it would be harmful to do it for `nix`.
