### ISSUE TITLE
channels.<name>.patches doesn't work if supportedSystems contains more than 1 architecture

### ISSUE THREAD

**Issue by ajgrf** [gytis-ivaskevicius/flake-utils-plus#96]
After adding a patch to `channels.nixpkgs.patches`, I get the following error:

```
error: a 'aarch64-linux' with features {} is required to build '/nix/store/is49g8n6gwyk91aa7pq6n1bnfy7pynmv-nixpkgs-patched-83667ff.drv', but I am a 'x86_64-linux' with features {benchmark, big-parallel, kvm, nixos-test}
```

If I then restrict `supportedSystems` to only include `x86_64-linux`, it works just fine on this machine. However, that's not an option in my case because I still need to support an `aarch64-linux` host.

**Comment by ajgrf** [comment]
OK, I think that makes sense now. I am getting this error when running `nixos-rebuild`, not just `nix flake show` or `nix flake check`. So I still think there is a bug somewhere.

**Comment by gytis-ivaskevicius** [comment]
Alright, it seems that the only solution here is to just have binfmt and/or build machines with required architectures since it is not possible to resolve this in any other way due to nix purity.

So the issue here is to patch nixpkgs we require `patch` command and since everything needs to be pure - `patch` needs to be taken from `aarch64-linux` packages which we can not execute since we are on the wrong architecture.
